Unicode Codes dataset update
datasets/unicode-characters pull request #1
Opened 2024-10-17 23:43 UTC by solo11

2024-10-17 23:45 UTC, solo11 commented
@anuveyatsu Let me know if there's anything I need to fix. Thanks!

2024-10-21 06:36 UTC, anuveyatsu commented on datapackage.json
> +  "name": "Unicode-Codes",
@solo11 this should be lower-case, here is the spec: https://specs.frictionlessdata.io/data-package/#metadata

2024-10-21 06:37 UTC, anuveyatsu commented on datapackage.json
> +  "title": "Unicode-Codes",
Not sure if this is any better than `name` attribute. Titles are a little more human-readable than identifiers.

2024-10-21 06:37 UTC, anuveyatsu commented on datapackage.json
> +      "path": "archive/source.csv",
I think we only want to include "data" files as resources but not archives.

2024-10-21 06:38 UTC, anuveyatsu commented on datapackage.json
> +      "pathType": "local",
@solo11 not sure which tool did you use to generate this. I think this one looks outdated.

2024-10-21 06:39 UTC, anuveyatsu commented on datapackage.json
> +      "path": "data/data.csv",
It's minor but I would name the file more descriptive and it is also a name of the resource. So `unicode.csv` or `unicode-chars.csv` is a better name.

2024-10-21 06:39 UTC, anuveyatsu commented on datapackage.json
> +      "path": "scripts/process.py",
Please, don't add scripts as data resources.

2024-10-21 06:39 UTC, anuveyatsu commented on datapackage.json
> +      "path": "scripts/requirements.tx",
ditto

2024-10-21 06:41 UTC, anuveyatsu commented on scripts/requirements.tx
Typo in file name `tx` -> `txt`. Also, if we didn't use pandas, we could go with all built-in libs :smile:

2024-10-21 06:41 UTC, anuveyatsu commented on README.md
> +datapackage:
Not sure if we want to have datapackage metadata as frontmatter here. @solo11 could you please let me know what was the intention here?

2024-10-21 06:43 UTC, anuveyatsu commented on README.md
> +  title: Unicode Codes
We could use this as a title in the `datapackage.json`

2024-10-21 06:43 UTC, anuveyatsu commented on README.md
> +  description: The Unicode Consortium is the standards body for the internationalization of software and services. Deployed on more than 20 billion devices around the world, Unicode also provides the
Not sure if this describes the dataset vs the Consortium.

2024-10-21 06:44 UTC, anuveyatsu commented on README.md
> +  created: 2024-01-01
is this coming from the source or why we choose this date as created date?

2024-10-21 06:44 UTC, anuveyatsu commented on README.md
> +  updated: 2024-01-31
is this coming from the source?

2024-10-21 06:49 UTC, anuveyatsu commented on README.md
> +| Field | Name | Status | Explanation |
Are these field information? If so, could we add it as table schema in the datapackage.json please?

2024-10-21 06:49 UTC, anuveyatsu requested changes
Hi @solo11 thanks for this PR - I left some comments, please, take a look 🙏🏼

2025-01-06 11:44 UTC, merged